# Generated by Django 5.1 on 2024-08-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
                ('time_start', models.DateTimeField()),
                ('date', models.DateField()),
                ('transcript', models.TextField()),
                ('entities', models.TextField()),
                ('keywords', models.TextField()),
                ('summary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.author')),
            ],
        ),
    ]
