# Generated by Django 5.1 on 2024-08-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('date', models.DateField()),
                ('audio_clips', models.ManyToManyField(to='clips.clip')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.author')),
                ('report_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportobjective')),
            ],
        ),
    ]
